function mesh = createCube()
% Create a mesh representing a unit cube.
%
%   Example
%   mesh = mv.TriMesh.createCube;
%   figure; axis equal; hold on; draw(mesh); view(3);
%   
%   See also 
%   draw, createOctahedron, createDodecahedron
%
vertices = [...
    0 0 0; ...
    1 0 0; ...
    0 1 0; ...
    1 1 0; ...
    0 0 1; ...
    1 0 1; ...
    0 1 1; ...
    1 1 1];

% faces are oriented such that normals point outwards
faces = [1 3 4 2;5 6 8 7;2 4 8 6;1 5 7 3;1 2 6 5;3 7 8 4];

mesh = mv.TriMesh(vertices, faces);
